pid                 nginx.pid;
error_log           error.log;

worker_processes  auto;
daemon off;

events {
    worker_connections 1024;
}

http {
    root        /;
    access_log  access.log;

    include     mime.types;
    sendfile    on;

    client_body_temp_path   client_body/;
    fastcgi_temp_path       fastcgi/;
    proxy_temp_path         proxy/;
    scgi_temp_path          scgi/;
    uwsgi_temp_path         uwsgi/;

    server {
        listen 9001;

        location /api/ {
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_pass http://localhost:3000/api/;
        }
        location /swagger-ui/ {
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_pass http://localhost:3000/swagger-ui/;
        }
        location /api-docs/ {
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_pass http://localhost:3000/api-docs/;
        }

        # location /r/ {
        #     root    .;
        # }

        location / {
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_pass http://localhost:9000/;
        }
    }
}
